import { type AppType } from 'next/dist/shared/lib/utils'
import { Poppins } from '@next/font/google'
import Head from 'next/head'
import '../styles/globals.css'
import Header from '../components/Header'
import NextNProgress from 'nextjs-progressbar'
import type { ColorScheme } from '@mantine/core'
import { Container } from '@mantine/core'
import { Divider } from '@mantine/core'

import { useColorScheme } from '@mantine/hooks'
import { ColorSchemeProvider, Flex, MantineProvider } from '@mantine/core'
import { useState } from 'react'

const MyApp: AppType = ({ Component, pageProps }) => {
  const preferredColorScheme = useColorScheme()
  const [colorScheme, setColorScheme] =
    useState<ColorScheme>(preferredColorScheme)
  const toggleColorScheme = (value?: ColorScheme) =>
    setColorScheme(value || (colorScheme === 'dark' ? 'light' : 'dark'))

  return (
    <>
      <ColorSchemeProvider
        colorScheme={colorScheme}
        toggleColorScheme={toggleColorScheme}
      >
        <MantineProvider
          withGlobalStyles
          withNormalizeCSS
          theme={{
            /** Put your mantine theme override here */
            colorScheme: preferredColorScheme,
          }}
        >
          <Head>
            <title>PokeNext</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <NextNProgress
            color="rgb(94 234 212)"
            startPosition={0.3}
            stopDelayMs={200}
            height={2}
            showOnShallow={true}
          />
          <Flex
            direction={'column'}
            sx={{
              minHeight: '100vh',
            }}
          >
            <Header />
            <Divider
              my="sm"
              sx={(theme) => ({
                marginLeft: theme.spacing.xl,
                marginRight: theme.spacing.xl,
                borderTopColor: theme.colors.green[9],
              })}
            />
            <Flex
              sx={{
                display: 'flex',
                flexDirection: 'column',
                flexGrow: 1,
              }}
            >
              <Component {...pageProps} />
            </Flex>
          </Flex>
        </MantineProvider>
      </ColorSchemeProvider>
    </>
  )
}

export default MyApp
